# Generated by Django 6.0.3 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="technicians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technician_name",
                    models.CharField(max_length=50, verbose_name="technician name"),
                ),
                (
                    "tech_email",
                    models.CharField(max_length=100, verbose_name="Serviceman email"),
                ),
                (
                    "tech_phone",
                    models.CharField(max_length=8, verbose_name="Serviceman phone"),
                ),
                ("is_working", models.BooleanField(default=False)),
            ],
        ),
    ]
