# Generated by Django 6.0.3 on 2026-03-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0001_initial"),
        ("timesheets", "0002_rename_customer_timesheets_customer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="technicians",
            new_name="Technician",
        ),
    ]
