# Generated by Django 6.0.3 on 2026-05-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
