# Generated by Django 6.0.3 on 2026-05-09 06:07

from django.db import migrations
from core.permissions import Roles

def create_groups(apps, schema_editor):
        Group = apps.get_model('auth','Group')
        Group.objects.get_or_create(name=Roles.ADMIN)
        Group.objects.get_or_create(name=Roles.TECHNICIAN)
def remove_groups(apps,schema_editor):
      Group = apps.get_model('auth', 'Group')
      Group.objects.filter(name__in=[Roles.ADMIN, Roles.TECHNICIAN]).delete()

class Migration(migrations.Migration):    
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
          migrations.RunPython(create_groups,remove_groups)
    ]
