# Generated by Django 6.0.3 on 2026-05-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_customer_email"),
        ("technicians", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("dispatched", "Dispatched"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("emailed", "Emailed"),
                            ("signed", "Signed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_reported", models.TextField(blank=True)),
                ("actions_taken", models.TextField(blank=True)),
                ("equipment_serial", models.CharField(blank=True, max_length=100)),
                ("warranty", models.BooleanField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("job_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_report_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.customer",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="technicians.technician",
                    ),
                ),
            ],
        ),
    ]
