# Generated by Django 6.0.3 on 2026-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("dispatched", "Dispatched"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("emailed", "Emailed"),
                    ("signed", "Signed"),
                    ("cancelled", "Cancelled"),
                ],
                default="dispatched",
                max_length=20,
            ),
        ),
    ]
