# Generated by Django 6.0.3 on 2026-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="Contact Persons"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Company Name"),
                ),
                ("phone", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
