# Generated by Django 6.0.3 on 2026-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
