# Generated by Django 6.0.3 on 2026-03-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("technicians", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="timesheets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_date", models.DateField()),
                ("issue_reported", models.TextField()),
                ("actions_taken", models.TextField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("hours_worked", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "Technicians",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="technicians.technicians",
                    ),
                ),
            ],
        ),
    ]
