# Generated by Django 6.0.3 on 2026-03-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesheets",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="timesheets",
            old_name="Technicians",
            new_name="technicians",
        ),
    ]
