# Generated by Django 6.0.3 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0003_rename_timesheets_timesheet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesheet",
            old_name="technicians",
            new_name="technician",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="hours_worked",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
